version: '3'

services:
  clickhouse:
    container_name: clickhouse
    image: bitnami/clickhouse:latest
    env_file:
      - .env
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - clickhouse_data:/bitnami/clickhouse
    networks:
      - my-network

  load_data:
    build: .
    container_name: load_data
    networks:
      - my-network
    depends_on:
      - clickhouse


networks:
  my-network:
volumes:
  clickhouse_data: