version: '3.8'

services:
  clickhouse:
    container_name: clickhouse
    image: bitnami/clickhouse:latest
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=${PASSWORD}

    ports:
      - "8123:8123"
    networks:
      - my-network

  load_data:
    build: .
    container_name: load_data
    env_file: .env
    volumes:
      - data:/app/data
    networks:
      - my-network
    depends_on:
      - clickhouse
    restart: always


networks:
  my-network:
volumes:
  data: