version: '3'

services:
  clickhouse:
    container_name: clickhouse
    image: bitnami/clickhouse:latest
    env_file:
      - .env
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/bitnami/clickhouse
    networks:
      - my-network

  load_data:
    build: .
    container_name: load_data
#    volumes:
#      - data:/app/data
    networks:
      - my-network
    depends_on:
      - clickhouse
    restart: always


networks:
  my-network:
volumes:
  clickhouse_data: